{
    'name': 'Secure Eye',
    'version': '14.0.0',
    "category": "Sales,stock,Accounting",
    'summary': 'Sales,Accounting,Delivery',
    "author": "Planet-odoo",
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base','sale','analytic','hr_expense','hr','hr_timesheet','product','hr_recruitment', 'project','sale_project','purchase','mail','tds_withholding_tax_cv_14e','hr_maintenance','hr_holidays','sale_timesheet'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/mail_template.xml',
        'views/hr_expense.xml',
        'views/account_analytic.xml',
        'views/hr_views.xml',
        'views/product.xml',
        'views/sales_view.xml',
        'views/project_view.xml',
        'views/project_view.xml',
        'reports/sale_report_template_inherited.xml',
        'views/partner_view_inherited.xml',
        'views/purchase_view.xml',
        'views/account_move.xml',
        'views/mail_view.xml',
        'views/hr_holidays.xml',

         ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
