{
    'name': 'Secure Eye - HR',
    'version': '14.0.0',
    "category": "Human Resource",
    'summary': 'Human Resource',
    "author": "Planet-odoo",
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base','sale','analytic','hr_expense','hr','hr_timesheet','product','hr_recruitment', 'project','sale_project','purchase','mail','tds_withholding_tax_cv_14e','hr_maintenance','hr_holidays','sale_timesheet','hr_contract','se_custom'
                ,'survey','hr_recruitment_survey','website_hr_recruitment'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/access_rights_master_view.xml',
        'views/res_users_inherit_view.xml',
        'views/offer_letter_paper_format.xml',
        'views/hr_job_inherit_views.xml',
        'views/survey_view.xml',
        'views/interview_rating_view.xml',
        'views/candidate_offer_letter.xml',
        'views/candidate_offer_letter_action.xml',
        'views/hr_applicant_view.xml',
        'views/hr_contract.xml',
        'wizard/hr_analytics_wizard.xml',
        'wizard/accept_job_view.xml',
        'views/offer_letter_generation.xml',
        'views/offer_letter_action.xml',
        'views/offer_letter_details_view.xml',
        'views/employee.xml',
        'views/Irs_generation.xml',
        'views/Irs_action.xml',
        'views/job_apply_inherit.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
