from . import access_rights_master
from . import res_users_inherit
from . import hr_job_inherit
from . import hr_applicant
from . import hr_contract
from . import interview_sheet
from . import survey_inherited
from . import offer_letter_details
from . import employee
from . import offer_letter_ctc_report