from odoo import api, fields, models, _,tools
from datetime import datetime,date,timedelta


class HrEmployee(models.Model):
    _inherit = 'hr.employee'

    join_date = fields.Datetime("Date Of Joining")
    status = fields.Selection([('active', 'Active'), ('inactive', 'Inactive')], string="STATUS")
    employe_id = fields.Char(string='EMPLOYEE ID')
    ty_pe = fields.Selection([('trainee', 'Trainee'), ('employee', 'Employee'), ('contract', 'Contract')],
                             string='TYPE')
    # ty_pes = fields.Char(string='TYPE')
    new_name = fields.Char(string='Name')
    # fun_tions = fields.Char(string='FUNCTION')
    fun_tion = fields.Selection([('technical', 'Technical'), ('nontech', 'Non Tech'), ('support', 'Support')],
                                string='FUNCTION')
    design_tation = fields.Char(string='DESIGNATION')
    level = fields.Char(string='LEVEL')
    reporting_manager = fields.Char(string='REPORTING MANAGER')
    bachelors = fields.Char(string='BACHELORS')
    masters = fields.Char(string='MASTERS')
    aad_no = fields.Char(string='AADHAR NO', ondelete='cascade')
    person_email = fields.Char(string='PERSONAL EMAIL ID')
    dol = fields.Date("DOL")
    busi_ness = fields.Char(string='Business')
    rol_e = fields.Char(string='Role')
    emergence_details = fields.Char(string='Emecrgency Contact Details')
    bae_location = fields.Char(string='BASE LOCATION')
    reason_leave = fields.Char(string='Reason for leaving')
    busines_head = fields.Char(string='Business Head')
    date_resign = fields.Date("Date of resignation")
    resg_type = fields.Selection([('vol', 'Vol'), ('non_vol', 'Non Vol')], string='Vol/Non vol resignation')
    # resg_types = fields.Char(string='Vol/Non vol resignation')
    incen_flag = fields.Boolean(string='Incentive flag')
    certi_ficate = fields.Char(string='Certifications')
    prev_org = fields.Char(string='Previous organization')
    curr_proj = fields.Char(string='Current project')
    curent_resign = fields.Date("Current billability start date")
    skill = fields.Char(string='Skill')
    total_exp = fields.Float(string='Total Experience')
    total_exp_comp = fields.Float(string='Experience in company')
    total_exp_comp_proj = fields.Float(string='Experience in current project')
    current_billability = fields.Char(string='Current billability status')
    billability_per = fields.Char(string='Billability %')
    proj_mang = fields.Char(string='Project Manager')
    cost_mang = fields.Char(string='Cost Center')
    prev_proj = fields.Char(string='Previous project details')
    fix_ctc = fields.Float(string='Fixed CTC')
    join_bonus = fields.Float(string='Joining bonus')
    esop_allot = fields.Selection([('yes', 'Yes'), ('no', 'No')], string='ESOPs alloted')
    # esop_allots = fields.Char(string='ESOPs alloted')
    last_salary_incre = fields.Float(string='Last salary increment %')
    date_last_prog = fields.Date("Date of last progression")
    market_bench = fields.Char(string='Market benchmark')
    var_pay = fields.Char(string='Variable pay out')
    defer_bonus = fields.Float(string='Deferred bonus')
    perman_add = fields.Char(string='Permanent address')

