{
    'name': 'Pre Sales',
    'version': '14.0.0',
    "category": "Sales",
    'summary': 'Sales,',
    "author": "Planet-odoo",
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base','sale','analytic','hr_expense','hr','hr_timesheet','product','hr_recruitment', 'project','sale_project','purchase','mail','tds_withholding_tax_cv_14e','hr_maintenance','sale_timesheet','se_custom'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/confirm_quotation_view.xml',
        'views/sale_submission_view.xml',
        'views/reason_master_view.xml',
        'views/sale_report_inherit.xml',
        'views/questionaire_sales_view.xml',
        'views/proposal_view.xml',
        'reports/graph_sale_view.xml',
        'views/proposal_paper_format.xml',
        'views/techno_commercial_proposal.xml',
        'views/techno_commercial_proposal_action.xml',
        'views/technical_proposal.xml',
        'views/technical_proposal_action.xml',
        'views/commercial_proposal.xml',
        'views/commercial_proposal_action.xml',
        'views/alert_mail_cron.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
